import type { ResumeTemplateConfig, ResumeTemplateId, TemplatePreferences } from "@/types/template";

export const RESUME_TEMPLATES: ResumeTemplateConfig[] = [
  {
    id: "classic-business",
    name: "经典商务",
    description: "黑白灰、衬线标题、单栏布局与细分割线，适合正式岗位投递。",
    variant: "classic",
    defaultColor: "#2f3437",
    colorOptions: [
      { label: "石墨灰", value: "#2f3437" },
      { label: "商务黑", value: "#111827" },
      { label: "冷杉绿", value: "#36584a" },
      { label: "深海蓝", value: "#1f3a5f" },
    ],
    fontFamily: "Arial, 'Noto Sans SC', 'Microsoft YaHei', sans-serif",
    headingFontFamily: "Georgia, 'Times New Roman', 'Noto Serif SC', serif",
    columnLayout: "single",
    moduleOrder: ["summary", "coreSkills", "workExperience", "projectExperience", "skillsAndTools", "education"],
    spacing: "normal",
    avatarShape: "square",
    avatarPlacement: "header-right",
    cardStyle: "none",
    showContactIcons: false,
  },
  {
    id: "modern-minimal",
    name: "现代简约",
    description: "无衬线字体、左侧窄色条、双栏结构，突出联系方式与技能。",
    variant: "modern",
    defaultColor: "#0f766e",
    colorOptions: [
      { label: "松石绿", value: "#0f766e" },
      { label: "靛蓝", value: "#4f46e5" },
      { label: "玫红", value: "#be185d" },
      { label: "橙红", value: "#c2410c" },
    ],
    fontFamily: "'Inter', 'Noto Sans SC', 'Microsoft YaHei', Arial, sans-serif",
    headingFontFamily: "'Inter', 'Noto Sans SC', 'Microsoft YaHei', Arial, sans-serif",
    columnLayout: "two-column",
    moduleOrder: ["summary", "workExperience", "projectExperience", "education", "coreSkills", "skillsAndTools"],
    spacing: "airy",
    avatarShape: "circle",
    avatarPlacement: "sidebar",
    cardStyle: "none",
    showContactIcons: false,
  },
  {
    id: "tech-blue",
    name: "科技蓝",
    description: "深蓝 Header、图标化联系信息与清晰模块标题，适合技术与 AI 岗位。",
    variant: "tech",
    defaultColor: "#1d4ed8",
    colorOptions: [
      { label: "科技蓝", value: "#1d4ed8" },
      { label: "电光青", value: "#0891b2" },
      { label: "星夜紫", value: "#6d28d9" },
      { label: "数据绿", value: "#047857" },
    ],
    fontFamily: "'Noto Sans SC', 'Microsoft YaHei', Arial, sans-serif",
    headingFontFamily: "'Noto Sans SC', 'Microsoft YaHei', Arial, sans-serif",
    columnLayout: "single",
    moduleOrder: ["summary", "coreSkills", "workExperience", "projectExperience", "skillsAndTools", "education"],
    spacing: "compact",
    avatarShape: "square",
    avatarPlacement: "header-left",
    cardStyle: "subtle",
    showContactIcons: true,
  },
  {
    id: "creative-design",
    name: "创意设计",
    description: "头像居中、模块卡片化、圆角与浅色底纹，适合作品型表达。",
    variant: "creative",
    defaultColor: "#db2777",
    colorOptions: [
      { label: "莓果粉", value: "#db2777" },
      { label: "珊瑚橙", value: "#ea580c" },
      { label: "鲜亮紫", value: "#7c3aed" },
      { label: "湖水蓝", value: "#0284c7" },
    ],
    fontFamily: "'Noto Sans SC', 'Microsoft YaHei', Arial, sans-serif",
    headingFontFamily: "'Noto Sans SC', 'Microsoft YaHei', Arial, sans-serif",
    columnLayout: "single",
    moduleOrder: ["summary", "coreSkills", "projectExperience", "workExperience", "skillsAndTools", "education"],
    spacing: "airy",
    avatarShape: "circle",
    avatarPlacement: "center",
    cardStyle: "strong",
    showContactIcons: false,
  },
  {
    id: "black-gold",
    name: "极简黑金",
    description: "深色 Header 与金色强调线，正文克制留白，适合高级岗位。",
    variant: "blackGold",
    defaultColor: "#b48a2c",
    colorOptions: [
      { label: "鎏金", value: "#b48a2c" },
      { label: "古铜", value: "#a16207" },
      { label: "香槟", value: "#d6b25e" },
      { label: "铂金", value: "#9ca3af" },
    ],
    fontFamily: "'Noto Sans SC', 'Microsoft YaHei', Arial, sans-serif",
    headingFontFamily: "Georgia, 'Noto Serif SC', 'Times New Roman', serif",
    columnLayout: "single",
    moduleOrder: ["summary", "workExperience", "projectExperience", "coreSkills", "skillsAndTools", "education"],
    spacing: "normal",
    avatarShape: "square",
    avatarPlacement: "header-right",
    cardStyle: "none",
    showContactIcons: false,
  },
  {
    id: "deep-banner",
    name: "深海横幅",
    description: "复刻参考 PDF：灰度横幅、悬浮圆形头像、细线模块标题与高密度时间轴履历。",
    variant: "deepBanner",
    defaultColor: "#4a5052",
    colorOptions: [
      { label: "海雾灰", value: "#4a5052" },
      { label: "深墨黑", value: "#24282a" },
      { label: "沉静蓝", value: "#334155" },
      { label: "苔原绿", value: "#3f4d45" },
    ],
    fontFamily: "'Microsoft YaHei', 'PingFang SC', 'Noto Sans SC', Arial, sans-serif",
    headingFontFamily: "'Microsoft YaHei', 'PingFang SC', 'Noto Sans SC', Arial, sans-serif",
    columnLayout: "single",
    moduleOrder: ["summary", "workExperience", "projectExperience", "education", "coreSkills", "skillsAndTools"],
    spacing: "compact",
    avatarShape: "circle",
    avatarPlacement: "header-left",
    cardStyle: "none",
    showContactIcons: false,
  },
];

export const DEFAULT_TEMPLATE_PREFERENCES: TemplatePreferences = {
  selectedTemplateId: "classic-business",
  accentColor: RESUME_TEMPLATES[0].defaultColor,
  avatarImage: null,
  avatarCrop: {
    zoom: 100,
    positionX: 50,
    positionY: 50,
  },
  backgroundImage: null,
  backgroundOpacity: 12,
  backgroundMode: "center",
};

export function getResumeTemplate(id: ResumeTemplateId): ResumeTemplateConfig {
  return RESUME_TEMPLATES.find((template) => template.id === id) ?? RESUME_TEMPLATES[0];
}

export function getTemplateDefaultColor(id: ResumeTemplateId): string {
  return getResumeTemplate(id).defaultColor;
}
